branch-defaults:
  eb-deploy-setup:
    environment: YOUR ENVIRONMENT
    group_suffix: null
  master:
    environment: YOUR ENVIRONMENT
    group_suffix: null
environment-defaults:
  barc-prod:
    branch: null
    repository: null
global:
  application_name: YOUR APPLICATION NAME
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
